services:
  db:
    env_file: .env
    image: postgres:17
    volumes:
      - "postgres:/var/lib/postgresql/data"
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}"]
      interval: 3s
      timeout: 3s
      retries: 10

  symfonia:
    env_file: .env
    build: .
    environment:
      - DATABASE_HOST=db
      - DATABASE_USERNAME=${POSTGRES_USER:?}
      - DATABASE_PASSWORD=${POSTGRES_PASSWORD:?}
      - DATABASE_NAME=${POSTGRES_DB:?}
    depends_on:
      db:
        condition: service_healthy
      rauthy:
        condition: service_started
      nats:
        condition: service_started
    ports:
      - 3001:3001
      - 3002:3002
      - 3003:3003/tcp
      - 3003:3003/udp
    volumes:
      - ./config.toml:/app/config.toml

  nats:
    env_file: .env
    # If you'd like to supply a NATS configuration file, add it here by appending the flag
    # "-c /etc/nats-config.cfg" (without quotes),
    # then uncommenting the last line of the "volumes:" key.
    command: -js -sd /data
    ports:
      - 4222:4222
      # - 8222:8222 # Optional, HTTP management port for information reporting
      # - 6222:6222 # Optional, routing port for clustering
    volumes:
      - "nats:/data"
      - "./nats-config.cfg:/etc/nats-config.cfg"
volumes:
  postgres:
  nats:
