create table if not exists users
(
    id                  varchar(255)      not null
        primary key,
    username            varchar(255)      not null,
    discriminator       varchar(255)      not null,
    avatar              varchar(255)      null,
    accent_color        int               null,
    banner              varchar(255)      null,
    theme_colors        text              null,
    pronouns            varchar(255)      null,
    phone               varchar(255)      null,
    desktop             smallint           not null,
    mobile              smallint           not null,
    premium             smallint           not null,
    premium_type        smallint unsigned  not null,
    bot                 smallint           not null,
    bio                 varchar(255)      not null,
    `system`            smallint           not null,
    nsfw_allowed        smallint           not null,
    mfa_enabled         smallint           not null,
    webauthn_enabled    smallint default 0 not null,
    totp_secret         varchar(255)      null,
    totp_last_ticket    varchar(255)      null,
    created_at          timestamp          not null,
    premium_since       timestamp          null,
    verified            smallint           not null,
    disabled            smallint           not null,
    deleted             smallint           not null,
    email               varchar(255)      null,
    flags               bigint unsigned   not null,
    public_flags        int unsigned      not null,
    purchased_flags     int               not null,
    premium_usage_flags int               not null,
    rights              bigint            not null,
    data                text              not null,
    fingerprints        text              not null,
    extended_settings   text              not null,
    settingsIndex       bigint unsigned   null,
    constraint users_settingsIndex_uindex
        unique (settingsIndex),
    constraint users_user_settings_index_fk
        foreign key (settingsIndex) references user_settings (`index`)
);

