use serde::{Deserialize, Serialize};

use crate::util::config::types::subconfigs::guild::{
    autojoin::AutoJoinConfiguration, discovery::DiscoverConfiguration,
};

#[derive(Debug, PartialEq, Eq, Clone, Copy, Serialize, Deserialize)]
#[serde(rename_all = "UPPERCASE")]
pub enum GuildFeatures {
    Activities_Alpha,
    Activities_Employee,
    Activities_Internal_Dev,
    Animated_Banner,
    Animated_Icon,
    Application_Command_Permissions_V2,
    Auto_Moderation,
    AutoMod_Trigger_Keyword_Filter,
    AutoMod_Trigger_ML_Spam_Filter,
    AutoMod_Trigger_Spam_Link_Filter,
    AutoMod_Trigger_User_Profile,
    Banner,
    BFG,
    Boosting_Tiers_Experiment_Medium_Guild,
    Boosting_Tiers_Experiment_Small_Guild,
    Bot_Developer_Early_Access,
    Burst_Reactions,
    Community_Canary,
    Community_Exp_Large_Gated,
    Community_Exp_Large_Ungated,
    Community_Exp_Medium,
    Channel_Emojis_Generated,
    Channel_Highlights,
    Channel_Highlights_Disabled,
    Clyde_Enabled,
    Clyde_Experiment_Enabled,
    Clyde_Disabled,
    Community,
    Creator_Accepted_New_Terms,
    Creator_Monetizable,
    Creator_Monetizable_Disabled,
    Creator_Monetizable_Pending_New_Owner_Onboarding,
    Creator_Monetizable_Provisional,
    Creator_Monetizable_Restricted,
    Creator_Monetizable_Whiteglove,
    Creator_Monetizable_Application_Allowlist,
    Create_Store_Page,
    Developer_Support_Server,
    Discoverable_Disabled,
    Discoverable,
    Enabled_Discoverable_Before,
    Exposed_To_Activities_WTP_Experiment,
    Guests_Enabled,
    Guild_Automod_Default_List,
    Guild_Communication_Disabled_Guilds,
    Guild_Home_Deprecation_Override,
    Guild_Home_Override,
    Guild_Home_Test,
    Guild_Member_Verification_Experiment,
    Guild_Onboarding,
    Guild_Onboarding_Admin_Only,
    Guild_Onboarding_Ever_Enabled,
    Guild_Onboarding_Has_Prompts,
    Guild_Role_Subscription,
    Guild_Role_Subscription_Purchase_Feedback_Loop,
    Guild_Role_Subscription_Trials,
    Guild_Server_Guide,
    Guild_Web_Page_Vanity_URL,
    Had_Early_Activities_Access,
    Has_Directory_Entry,
    Hide_From_Experiment_UI,
    Hub,
    Increased_Thread_Limit,
    Internal_Employee_Only,
    Invite_Splash,
    Invites_Disabled,
    Linked_To_Hub,
    Marketplaces_Connection_Roles,
    Member_Profiles,
    Member_Verification_Gate_Enabled,
    Member_Verification_Manual_Approval,
    Mobile_Web_Role_Subscription_Purchase_Page,
    Monetization_Enabled,
    More_Emoji,
    More_Stickers,
    News,
    New_Thread_Permissions,
    Partnered,
    Premium_Tier_3_Override,
    Preview_Enabled,
    Raid_Alerts_Disabled,
    Relay_Enabled,
    Restrict_Spam_Risk_Guild,
    Role_Icons,
    Role_Subscriptions_Available_For_Purchase,
    Role_Subscriptions_Enabled,
    Role_Subscriptions_Enabled_For_Purchase,
    Shard,
    Shared_Canvas_Friends_And_Family_Test,
    Soundboard,
    Summaries_Enabled,
    Summaries_Enabled_GA,
    Summaries_Disabled_By_User,
    Summaries_Enabled_By_User,
    Text_In_Stage_Enabled,
    Text_In_Voice_Enabled,
    Threads_Enabled_Testing,
    Threads_Enabled,
    Thread_Default_Auto_Archive_Duration,
    Threads_Only_Channel,
    Ticketed_Events_Enabled,
    Ticketing_Enabled,
    Vanity_Urls,
    Verified,
    VIP_Regions,
    Voice_Channel_Effects,
    Welcome_Screen_Enabled,
}

#[derive(Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct GuildConfiguration {
    pub discovery: DiscoverConfiguration,
    pub auto_join: AutoJoinConfiguration,
    pub default_features: Vec<GuildFeatures>,
}
