name: "General: License headers and identifiers"

on:
  push:
    branches: ["main"]
    tags: ["*"]
  pull_request:
    branches: ["*"]
  workflow_dispatch:

jobs:
  license-headers:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Check license headers
        run: npx github:viperproject/check-license-header#v1 check --strict --config ./.github/license-check/config.json --path .
